apiVersion: apps/v1
kind: Deployment
metadata:
  name: ada-front
spec:
  selector:
    matchLabels:
      app: ada-front
  template:
    metadata:
      labels:
        app: ada-front
    spec:
      containers:
      - name: ada-front-image
        image: cyborgmg/ada-front:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
          - name: API_URL
            value: '192.168.49.2:31194'
      volumes:
        - name: ada-front-volume
          persistentVolumeClaim:
              claimName: ada-front-pvc