apiVersion: v1
kind: Service
metadata:
  name: ada-front
  labels:
    app: ada-front
spec:
  type: NodePort
  selector:
    app: ada-front
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 31195