apiVersion: apps/v1
kind: Deployment
metadata:
  name: ada-api
spec:
  selector:
    matchLabels:
      app: ada-api
  template:
    metadata:
      labels:
        app: ada-api
    spec:
      containers:
      - name: ada-api-image
        image: cyborgmg/ada:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: DATASOURCE_URL
            value: 'jdbc:postgresql://postgres:5432/mcm'
          - name: DATASOURCE_USER
            value: 'mcm'
          - name: DATASOURCE_PASSWD
            value: 'mcm'
          - name: DATASOURCE_DRIVER
            value: 'org.postgresql.Driver'
          - name: DATASOURCE_URL_TEST
            value: 'jdbc:postgresql://postgres:5432/mcm_test'
          - name: DATASOURCE_USER_TEST
            value: 'mcm_test'
          - name: DATASOURCE_PASSWD_TEST
            value: 'mcm_test'
          - name: DATASOURCE_DRIVER_TEST
            value: 'org.postgresql.Driver'
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PASS
            value: 'c6b94gmg'
          - name: REDIS_PORT
            value: '6379'
      volumes:
        - name: ada-api-volume
          persistentVolumeClaim:
              claimName: ada-api-pvc