apiVersion: v1
kind: Service
metadata:
  name: ada-api
  labels:
    app: ada-api
spec:
  type: LoadBalancer
  selector:
    app: ada-api
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 31194